### ISSUE TITLE
Bigom Contracts Review

### ISSUE THREAD

**Issue by trantho3910** [bigbomio/digital-contracts#18]
After review this source code I see architecture design very perfect and easy to learn. In technical-docs folder I can see the overview of this contract. I can understand the life cycle and the interaction between the hirer and the freelancer through the smart contract. Source code structure very easy to understand. I see more one library and function that I not using before like 'ipfs-api', 'encodePacked', 'keccak256', . I need more document about key 'status' [2,4,5,9]. In each function I can understand input, output, code logic. I have the question about function createJob(bytes jobHash, uint expired, uint256 budget, string category) in parameter category you are using string which is not Enums or uint (you can modify [1 : Banking, 2 Developer, 3 Design]). In deploy function, in config file of Truffle I do not see information about Testnet like Ropsten. Have you deployed this contract to real Testnet?. In function createJob, why didn't you check valid budget and balance of owner?
 Perfect source code, I think I will learned more from this project

**Comment by onimsha** [comment]
Thanks @trantho3910
